### ISSUE TITLE
Java source directories should not contain dots

### ISSUE THREAD

**Issue by Hanicef** [ArastoSahbaei/toberenamed#15]
The directory `com.tobenamed `in `/src/main/java` should be renamed to `com/tobenamed`, as strange stuff happens in generated the `.jar` file when dots are encountered in paths, which could lead to issues in the future.

A look within the `.jar` file reveals the discrepancy:
```
...
META-INF/maven/
META-INF/maven/com.tobenamed/
META-INF/maven/com.tobenamed/tobenamed/
com/tobenamed/Application.class
application.properties
META-INF/maven/com.tobenamed/tobenamed/pom.xml
META-INF/maven/com.tobenamed/tobenamed/pom.properties
```

Note how the `META-INF` directory treats the dot differently as opposed to the `com` directory.

**Comment by ArastoSahbaei** [comment]
Nice Catch Mr.Cyborg 👍👍👍

**Comment by ArastoSahbaei** [comment]
The SpringBoot project automatically changes from "/" to "." when you refactor.
It seems the project wants the dots?

**Comment by ArastoSahbaei** [comment]
Intelliji issue, now solved.
